Perform\NotificationBundle\Entity\NotificationLog:
    type: entity
    table: perform_notification_notification_log
    repositoryClass: Perform\NotificationBundle\Repository\NotificationLogRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        type:
            type: string
        content:
            type: text
        status:
            type: smallint
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        recipient:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            joinColumn:
                nullable: true
