services:
    admin_notification.notifier:
        class: Admin\NotificationBundle\Notifier

    admin_notification.publisher.local:
        class: Admin\NotificationBundle\Publisher\LocalPublisher
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
        tags:
            - {name: admin_notification.publisher}

    admin_notification.publisher.logger:
        class: Admin\NotificationBundle\Publisher\LoggerPublisher
        arguments:
            - "@logger"
        tags:
            - {name: admin_notification.publisher}

    admin_notification.publisher.email:
        class: Admin\NotificationBundle\Publisher\EmailPublisher
        arguments:
            - "@admin_base.email.mailer"
            - "@templating"
        tags:
            - {name: admin_notification.publisher}

    admin_notification.repository.notification_log:
        class: Admin\NotificationBundle\Repository\NotificationLogRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
          - AdminNotificationBundle:NotificationLog

    admin_notification.provider.current_user:
        class: Admin\NotificationBundle\RecipientProvider\CurrentUserProvider
        arguments: ["@security.token_storage"]

    admin_notification.provider.settings:
        class: Admin\NotificationBundle\RecipientProvider\SettingsProvider
        arguments: ["@doctrine.orm.entity_manager", "@admin_base.settings_manager"]

    admin_notification.twig.notification:
        class: Admin\NotificationBundle\Twig\Extension\NotificationExtension
        arguments: ['@admin_notification.provider.current_user', '@admin_notification.repository.notification_log']
        tags:
            - {name: twig.extension}
