services:
    admin_notification.publisher.local:
        class: Admin\NotificationBundle\Publisher\LocalPublisher
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"

    admin_notification.publisher.logger:
        class: Admin\NotificationBundle\Publisher\LoggerPublisher
        arguments:
            - "@logger"

    admin_notification.notifier:
        class: Admin\NotificationBundle\Notifier
        calls:
            - [addPublisher, ["@admin_notification.publisher.local"]]
            - [addPublisher, ["@admin_notification.publisher.logger"]]

    admin_notification.repository.notification_log:
        class: Admin\NotificationBundle\Repository\NotificationLogRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
          - AdminNotificationBundle:NotificationLog

    admin_notification.recipient_provider.default:
        class: Admin\NotificationBundle\RecipientProvider\DefaultRecipientProvider
        arguments: ["@security.token_storage"]

    admin_notification.twig.notification:
        class: Admin\NotificationBundle\Twig\Extension\NotificationExtension
        arguments: ['@admin_notification.recipient_provider.default', '@admin_notification.repository.notification_log']
        tags:
            - {name: twig.extension}
