services:
    perform_notification.notifier:
        class: Perform\NotificationBundle\Notifier\Notifier
        arguments:
            - ''
            - '@event_dispatcher'

    Perform\NotificationBundle\Notifier\Notifier: '@perform_notification.notifier'

    perform_notification.renderer:
        class: Perform\NotificationBundle\Renderer\TwigRenderer
        arguments:
            - "@twig"

    perform_notification.publisher.local:
        class: Perform\NotificationBundle\Publisher\LocalPublisher
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_notification.renderer"
        tags:
            - {name: perform_notification.publisher, alias: local}

    perform_notification.publisher.email:
        class: Perform\NotificationBundle\Publisher\EmailPublisher
        arguments:
            - "@swiftmailer.mailer"
            - "@perform_notification.renderer"
            - '%perform_notification.email_default_from%'
        tags:
            - {name: perform_notification.publisher, alias: email}

    perform_notification.repository.notification_log:
        class: Perform\NotificationBundle\Repository\NotificationLogRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
          - PerformNotificationBundle:NotificationLog

    perform_notification.provider.current_user:
        class: Perform\NotificationBundle\RecipientProvider\CurrentUserProvider
        arguments: ["@security.token_storage"]

    perform_notification.provider.settings:
        class: Perform\NotificationBundle\RecipientProvider\SettingsProvider
        arguments: ["@doctrine.orm.entity_manager", "@perform_base.settings_manager"]

    perform_notification.twig.notification:
        class: Perform\NotificationBundle\Twig\Extension\NotificationExtension
        arguments: ['@perform_notification.provider.current_user', '@perform_notification.repository.notification_log']
        tags:
            - {name: twig.extension}

    perform_notification.data_collector:
        class: Perform\NotificationBundle\DataCollector\NotificationsDataCollector
        public: false
        arguments:
            - '@perform_notification.notifier'
        tags:
            -
                name: data_collector
                template: '@PerformNotification/data_collector/notifications.html.twig'
                id: 'perform_notification'
